# Generated by Django 5.0 on 2023-12-08 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=100)),
                ('taskModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.taskmodel')),
            ],
        ),
    ]
