# Generated by Django 5.0 on 2023-12-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='isCompleted',
            field=models.BooleanField(default=False, verbose_name='Task Completed?'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='taskAssignDate',
            field=models.DateField(verbose_name='Task Assign Date'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='taskDescription',
            field=models.TextField(verbose_name='Task Description'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='taskTitle',
            field=models.CharField(max_length=100, verbose_name='Task Title'),
        ),
    ]
